### ISSUE TITLE
Under "manage servers", clicking a server causes yapdnsui to crash.

### ISSUE THREAD

**Issue by kdfreeheart** [xbgmsharp/yapdnsui#6]
Clicking on a link in the "manage servers" section causes yapdnsui to crash.

Arch: amd64
OS: Ubuntu Vivid (15.04)
Node: v0.12.7
Bower: 1.5.2
yapdnsui version: Commit 089e762d5b78a06b46fb8fc7e00b205e484f22ac
Launch command: HOST=0.0.0.0 PORT=8080 DEBUG=yapdnsui node bin/www

Full output from launch to error:
  yapdnsui Express server listening on port 8080 +0ms
db.list [{"id":1,"name":"192.168.103.104:8053","url":"http://192.168.103.104:8053","password":"changeme","pdns_type":null,"pdns_id":null,"pdns_url":null,"pdns_daemon_type":null,"pdns_version":null,"pdns_config_url":null,"pdns_zones_url":null}]
GET / 304 675.712 ms - -
GET /stylesheets/gh-fork-ribbon.css 304 3.334 ms - -
GET /bootstrap/dist/css/bootstrap.min.css 304 15.493 ms - -
GET /bootstrap/dist/css/bootstrap-theme.min.css 304 11.087 ms - -
GET /font-awesome/css/font-awesome.min.css 304 9.122 ms - -
GET /datatables/media/css/dataTables.bootstrap.min.css 304 8.121 ms - -
GET /pnotify/pnotify.core.css 304 7.566 ms - -
GET /stylesheets/style.css 304 0.299 ms - -
GET /jquery/dist/jquery.min.js 304 1.656 ms - -
GET /jqueryui/jquery-ui.min.js 304 1.679 ms - -
GET /bootstrap/dist/js/bootstrap.min.js 304 1.463 ms - -
db.list [{"id":1,"name":"192.168.103.104:8053","url":"http://192.168.103.104:8053","password":"changeme","pdns_type":null,"pdns_id":null,"pdns_url":null,"pdns_daemon_type":null,"pdns_version":null,"pdns_config_url":null,"pdns_zones_url":null}]
GET /servers 304 286.900 ms - -
GET /stylesheets/gh-fork-ribbon.css 304 0.964 ms - -
GET /bootstrap/dist/css/bootstrap.min.css 304 10.355 ms - -
GET /bootstrap/dist/css/bootstrap-theme.min.css 304 10.409 ms - -
GET /font-awesome/css/font-awesome.min.css 304 10.751 ms - -
GET /datatables/media/css/dataTables.bootstrap.min.css 304 4.977 ms - -
GET /pnotify/pnotify.core.css 304 4.841 ms - -
GET /stylesheets/style.css 304 2.786 ms - -
GET /jquery/dist/jquery.min.js 304 4.108 ms - -
GET /jqueryui/jquery-ui.min.js 304 4.235 ms - -
GET /bootstrap/dist/js/bootstrap.min.js 304 4.833 ms - -
GET /datatables/media/js/jquery.dataTables.min.js 304 5.258 ms - -
GET /datatables/media/js/dataTables.bootstrap.min.js 304 4.217 ms - -
GET /pnotify/pnotify.core.js 304 1.080 ms - -
GET /bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 304 1.011 ms - -
server_id: [1]
1
db.get [object Object]
db.list [{"id":1,"name":"192.168.103.104:8053","url":"http://192.168.103.104:8053","password":"changeme","pdns_type":null,"pdns_id":null,"pdns_url":null,"pdns_daemon_type":null,"pdns_version":null,"pdns_config_url":null,"pdns_zones_url":null}]
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/src/yapdnsui/routes/servers.js:61:23
    at Request._callback (/usr/src/yapdnsui/libs/pdns/config.js:14:25)
    at self.callback (/usr/src/yapdnsui/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/usr/src/yapdnsui/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14

**Comment by jh1806** [comment]
I am also having the same issue. Installed as per the guide on GitHub. When trying to access a server, node.js crashes with the same error as above: "SyntaxError: Unexpected token u".

**Comment by piwats** [comment]
same here

**Comment by herveleclerc** [comment]
If you are using 4.x you shoud append to the server url /api/v1
eg: http://xxx.xxx.xx.xx/api/v1
