### ISSUE TITLE
Layout / Images not loading. Missing dependencies?

### ISSUE THREAD

**Issue by broedli** [xbgmsharp/yapdnsui#9]
Hi there, I just wanted to try out your good looking yapdnsui but I must have done something terrible wrong.

This is how it looks: 
![broken layout](http://i.imgur.com/50ICKrP.png)

```
# node -v
v5.9.0
```

```
$ HOST=127.0.0.1 PORT=8080 DEBUG=yapdnsui node bin/www
--------
  yapdnsui Express server listening on port 8080 +0ms
db.list [{"id":1,"name":"localhost","url":"https://localhost:8053","password":"changeme","pdns_type":null,"pdns_id":null,"pdns_url":null,"pdns_daemon_type":null,"pdns_version":null,"pdns_config_url":null,"pdns_zones_url":null}]
GET / 304 252.333 ms - -
GET /bootstrap/dist/css/bootstrap.min.css 404 54.385 ms - 2822
GET /bootstrap/dist/css/bootstrap-theme.min.css 404 81.758 ms - 2822
GET /stylesheets/style.css 304 2.001 ms - -
GET /stylesheets/gh-fork-ribbon.css 304 1.848 ms - -
GET /font-awesome/css/font-awesome.min.css 404 27.220 ms - 2822
GET /datatables/media/css/dataTables.bootstrap.min.css 404 45.252 ms - 2822
GET /pnotify/pnotify.core.css 404 69.666 ms - 2822
GET /jquery/dist/jquery.min.js 404 93.424 ms - 2822
GET /jqueryui/jquery-ui.min.js 404 41.507 ms - 2822
GET /bootstrap/dist/js/bootstrap.min.js 404 67.104 ms - 2822
```

I also noticed a crash when clicking on the localhost entry.

```
server_id: [1]
1
db.get [object Object]
db.list [{"id":1,"name":"localhost","url":"https://localhost:8053","password":"changeme","pdns_type":null,"pdns_id":null,"pdns_url":null,"pdns_daemon_type":null,"pdns_version":null,"pdns_config_url":null,"pdns_zones_url":null}]
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /home/timo/Github/yapdnsui/routes/servers.js:61:23
    at Request._callback (/home/timo/Github/yapdnsui/libs/pdns/config.js:14:25)
    at self.callback (/home/timo/Github/yapdnsui/node_modules/request/request.js:198:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (/home/timo/Github/yapdnsui/node_modules/request/request.js:877:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
```

What dependencies am I missing?

**Comment by broedli** [comment]
Was missing bower and `bower install`. Since bower wasn't listed as dependency ... ah, nvm I was just blind.
